export const terms = [
    "Öffnungszeiten der Einrichtung",
"Änderungen Betriebskonzept Prostitutionsvermittlung",
"Änderungen Betriebskonzept Prostitutionsveranstaltung",
"Änderungen Betriebskonzept Prostitutionsstätte",
"Änderungen Betriebskonzept Prostitutionsfahrzeug",
"Änderung der Unternehmensdaten",
"§ 33a Gewerbeordnung",
"sonstige Unterlagen",
"persönliche Daten",
"niederlassungEn_editgrid_editgrid",
"Zuständige/r Unfallversicherungsträger:in",
"Zustimmung zu der Zuverlässigkeitsprüfung",
"Zustelladresse der Fahrschulerlaubnis",
"Zustelladresse der Fahrlehrlaubnis",
"Zustelladresse der Fahrlehrerlaubnis",
"Zustelladresse der Fahrlehrererlaubnis",
"Zustelladresse der Betriebserlaubnis",
"Zusammengesetzte Rechtsform: Angaben der anzeigestellenden Person(en)",
"Zusammengesetzte Rechtsform: Angaben der anzeigenden Person(en)",
"Zusammengesetzte Rechtsform: Angaben der anzeigende Person(en)",
"Zusammengesetzte Rechtsform: Angaben der antragstellenden Person(en)",
"Zusammengesetzte Rechtsform: Angaben der antragstellenden Person",
"Zusammengesetzte Rechtsform: Angaben der Antragstellenden",
"Zusammenfassung der Datenübermittlung",
"Zusammenfassung",
"Zur Verkehrsleitung",
"Zum Unternehmen",
"Worum geht es bei der ausgewählten Verwaltungsleistung?",
"Worum geht es bei der Dienstleistung?",
"Worum geht es bei dem Antragsverfahren?",
"Werbung",
"Wer ist für die Bearbeitung zuständig?",
"Welche Voraussetzungen müssen erfüllt sein?",
"Welche Unterlagen werden benötigt?",
"Welche Gebühren fallen an?",
"Welche Fristen sind zu beachten?",
"Weitere geschäftsführende Person.",
"Weitere Wettvermittlungs- bzw. Wettannahmestelle",
"Weitere Betriebsstätten/Filialen",
"Weitere Betriebe",
"Weitere Angebote",
"Was sind die Rechtsgrundlagen?",
"Verzeichnis der Biostoffe, Wartungskonzept und Tätigkeitsbeschreibung",
"Verwender:in",
"Vertragsparteien",
"Versicherung",
"Verpflichteteneigenschaft",
"Vermittlungsformen",
"Verlängerung der Erlaubnis",
"Verdachtsfälle und Sonstiges",
"Verantwortliche Personen nach § 13 Abs. 2 Arbeitsschutzgesetz (ArbSchG)",
"Verantwortliche Personen nach § 13 Abs. 2 ArbSchG",
"Verantwortliche Person",
"Veranstaltungskonzept",
"Veranstaltungsdaten",
"Veranstaltungsbeschreibung",
"Veranstaltungsablauf",
"Unternehmensregistrierung und/oder Ermächtigungen - Pflanzen",
"Unternehmensregistrierung und/oder Ermächtigungen - Holz",
"Unternehmensregistrierung und/oder Ermächtigungen",
"Unternehmensgruppe",
"Unternehmensdaten",
"Unternehmens- und Geschäftsbezeichnung (nach § 31a Abs. 1 Nr. 1 GWB)",
"Unternehmens- und Geschäftsbezeichnung",
"Unterlagen zur Stellvertretung",
"Umfang der Datenübermittlung",
"Umfang der Anzeige",
"Tätigkeiten mit Krankheitserregern",
"Tätige/Beschäftigte und Kunden",
"Typische Veranstaltungsabläufe",
"Typische Betriebsabläufe",
"Stiftung",
"Spezifiziertes Material",
"Spezielle Angaben",
"Sozialräume und Aufbewahrungsmöglichkeiten",
"Sorgfaltspflichten für die Kundschaft",
"Sonstiges",
"Sonstiger Hinweis",
"Sonstige Unterlagen",
"Sitz der antragstellenden Firma",
"Schutz- und Sicherheitsmaßnahmen: Angaben zu den Prostituierten",
"Schutz- und Sicherheitsmaßnahmen",
"Sanitäranlagen und Umkleidemöglichkeiten",
"Sanitäranlagen",
"Sachkundige Personen",
"Räumlichkeiten und Ausstattung",
"Räumlichkeiten",
"Risikomanagement",
"Rechtsform (nach § 31a Abs. 1 Nr. 3 GWB)",
"Rechtsform",
"Qualifikation der verantwortlichen Personen",
"Projektleitungen und Beauftragten für die Biologische Sicherheit (BBS)",
"Projektleitungen und Beauftragte für die Biologische Sicherheit (BBS)",
"Projektleiter:in und Beauftragte:r für die Biologische Sicherheit (BBS)",
"Produktangaben",
"Preisgestaltung und Abwicklung der Zahlung",
"Preis- und Angebotsgestaltung",
"Pflanzenpass",
"Persönliche Daten",
"Persönliche Angaben zum/zur Träger:in der Krankenhausapotheke",
"Persönliche Angaben des/der künftigen Betriebserlaubnisinhaber:in",
"Persönliche Angaben der Person, die die Erlaubnis erhält",
"Persönliche Angaben",
"Personengesellschaft: Angaben der anzeigestellenden Person(en)",
"Personengesellschaft: Angaben der anzeigenden Person(en)",
"Personengesellschaft: Angaben der antragstellenden Person(en)",
"Personengesellschaft: Angaben der antragstellenden Person",
"Personengesellschaft: Angaben der Antragstellenden",
"Personenbezogene Nachweise",
"Personen, die sexuelle Dienstleistungen anbieten, und Kundschaft",
"Personen, die sexuelle Dienstleistungen anbieten und Kundschaft",
"Personalaufstellung",
"Personal",
"Panel",
"Organisatorische Abläufe und Rahmenbedingungen",
"OHG-Vertrag oder GbR-Vertrag",
"Niederlassungen",
"Nachweise zur verantwortlichen Person des Großhandels gemäß § 52a Abs. 2 Nr. 3 AMG",
"Nachweise zur antragstellenden Person",
"Nachweise zum/zur Gesellschafter:in",
"Nachweise zum Großhandelsunternehmen",
"Nachweise von der bevollmächtigten Person",
"Nachweise der juristischen Person",
"Nachweise der antragstellenden Person",
"Nachweise",
"Nachweis der verantwortlichen Person nach § 52a Abs. 2 Nr. 3 AMG",
"Nachweis der bevollmächtigten Person",
"Nachweis der Mindestanforderungen",
"NRW LP",
"Messgeräte",
"Messgerät",
"Maßnahmen zum Schutz von zur Schau gestellten Personen und Dritten",
"Maßnahmen der arbeitsmedizinischen Vorsorge (Pflicht-, Angebotsvorsorge gemäß Verordnung zur arbeitsmedizinischen Vorsorge (ArbMedVV))",
"Liste der zu kontrollierenden Waren",
"Leistungsauswahl",
"Landing Page",
"Lagerstätte",
"Kundschaft",
"Kosten",
"Kontrollstelle",
"Kinder und weitere Haushaltsangehörige",
"Kenntnisnahme Originaldokumente",
"Kenntnisnahme Antrags-ID",
"Kenntnisnahme Antrags ID - Änderungen in einem Prostitutionsgewerbe",
"Kenntnisnahme Antrags ID - Stellvertretungserlaubnis befristet",
"Kenntnisnahme Antrags ID - Prostitutionsfahrzeug Erlaubnis Verlängerung",
"Kenntnisnahme",
"Juristische Person: Angaben zur gesetzlichen Vertretung der antragstellenden Person",
"Juristische Person: Angaben der gesetzlichen Vertretung",
"Juristische Person: Angaben der antragstellenden Person",
"Institution",
"Instandsetzer:in",
"Innehabende Person eines Kehrbezirks",
"Import aus Nicht-EU-Staaten",
"Ihre persönlichen Angaben",
"Hinweis, Bearbeitungsdauer und widerrechtliche Tätigkeit",
"Hinweis zur gebührenpflichtigen Anmeldung",
"Hinweis zur Gültigkeit anderer Rechtsvorschriften",
"Hinweis zu den Kosten und Entgelten",
"Hinweis zu Nachweisen",
"Hinweis zu Fristen und Genehmigungsfiktion",
"Hinweis widerrechtliche Tätigkeit",
"Hinweis Zuverlässigkeit",
"Hinweis Veröffentlichung im Kontrollstellenverzeichnis",
"Hinweis Verwaltungskosten",
"Hinweis Verwaltungsgebühr",
"Hinweis Verträge der Wasserwirtschaft",
"Hinweis Verfügbarkeit",
"Hinweis Unternehmerpflichten",
"Hinweis Unternehmenspflichten",
"Hinweis Originaldokumente",
"Hinweis Datenschutz",
"Hinweis Bearbeitungsdauer und widerrechtliche Tätigkeit HIDDEN",
"Hinweis Bearbeitungsdauer und widerrechtliche Tätigkeit",
"Hinweis Bearbeitungsdauer",
"Hinweis Auflagen und Verpflichtungen",
"Hidden Fields (nicht löschen)",
"Gruppenstruktur",
"Gewerbliche Tätigkeiten",
"Geschäftliche Adress- und Kontak"
];